let games = [
    {
        id:1,
        nome: 'Red Dead Redemption 2',
        sinopse: 'Red Dead Redemption 2, a épica aventura de mundo aberto da Rockstar Games aclamada pela crítica e o jogo mais bem avaliado desta geração de consoles, agora chega aprimorado para PC com conteúdos inéditos no Modo História, melhorias visuais e muito mais.',      
        desenvolvedora: 'Rockstar Games',
        lançamento: '5/dez./2019',
        valor: '299,90',
        link:'https://store.steampowered.com/app/1174180/Red_Dead_Redemption_2/',
        video: 'https://www.youtube.com/embed/eaW0tYpxyp0',
        img: 'imagens/red.jpg',
    },
    {
        id: 2,
        nome: 'EA SPORTS FC 25',
        sinopse: 'O EA SPORTS FC™ 25 oferece mais maneiras de ganhar pelo clube. Jogue com suas amizades nos seus modos favoritos com o novo Rush 5x5 e leve seu clube à vitória com o FC IQ dando mais controle tático do que nunca.',
        desenvolvedora: 'EA Canada & EA Romania',
        lançamento: '27/set/2024',
        valor: '299,00',
        link:'https://store.steampowered.com/app/2669320/EA_SPORTS_FC_25/',
        video: 'https://www.youtube.com/embed/pBM2xyco_Kg',
        img: 'imagens/eafc.jpg',
    },
    {
        id: 3,
        nome: 'Counter-Strike 2',
        sinopse: 'Há mais de duas décadas, o Counter-Strike oferece uma experiência competitiva de elite moldada por milhões de jogadores mundialmente. Agora, o próximo capítulo da história do CS vai começar. Isso é Counter-Strike 2.',
        desenvolvedora: 'Valve',
        lançamento: '21/ago/2012',
        valor: 'Gratuito',
        link:'https://store.steampowered.com/app/730/CounterStrike_2/',
        video: 'https://www.youtube.com/embed/c80dVYcL69E',
        img: 'imagens/cs2.png',
    },
    {
        id: 4,
        nome: 'God of War Ragnarök',
        sinopse: 'Kratos e Atreus embarcam numa viagem mítica em busca de respostas antes da chegada do Ragnarök — agora no PC.',
        desenvolvedora: 'Santa Monica Studio, Jetpack Interactive',
        lançamento: '19/set/2024',
        valor: '249,90',
        link:'https://store.steampowered.com/app/2322010/God_of_War_Ragnark/',
        video: 'https://www.youtube.com/embed/hfJ4Km46A-0',
        img: 'imagens/god.jpg',
    },
    {
        id: 5,
        nome: 'Microsoft Flight Simulator 2024',
        sinopse: 'Explore o mundo com a nossa maior frota de aviões e leve a simulação a novas alturas em sua carreira de aviador com o Microsoft Flight Simulator 2024.',
        desenvolvedora: 'Asobo Studio',
        lançamento: '19/nov/2024',
        valor: '299,00',
        link:'https://store.steampowered.com/app/2537590/Microsoft_Flight_Simulator_2024/',
        video: 'https://www.youtube.com/embed/p3xp-SnZDoY',
        img: 'imagens/fly.jpg',
    },
    {
        id: 6,
        nome: 'Black Myth: Wukong',
        sinopse: 'Black Myth: Wukong é um RPG de ação inspirado na mitologia chinesa. Você assume o papel do Predestinado e tem a responsabilidade de encarar os desafios e as maravilhas do mundo para desvendar a verdade obscura por trás de uma lenda gloriosa do passado.',
        desenvolvedora: 'Game Science',
        lançamento: '19/ago/2024',
        valor: '229,99',
        link:'https://store.steampowered.com/app/2358720/Black_Myth_Wukong/',
        video: 'https://www.youtube.com/embed/pnSsgRJmsCc',
        img: 'imagens/black.jpg',
    },
    {
        id: 7,
        nome: 'Subnautica 2',
        sinopse: 'Mergulhe de cabeça em Subnautica 2, um jogo de sobrevivência em mar aberto. Jogue sozinho ou com amigos enquanto explora biomas atraentes e descobre criaturas fascinantes. Crie veículos, ferramentas e bases para sobreviver neste misterioso mundo alienígena.',
        desenvolvedora: 'Unknown Worlds Entertainment',
        lançamento: '2025',
        valor: 'Não Disponivel',
        link:'https://store.steampowered.com/app/1962700/Subnautica_2/',
        video: 'https://www.youtube.com/embed/WS0vTRl_2PQ',
        img: 'imagens/sub2.jpg',
    },
    {
        id: 8,
        nome: 'Little Nightmares III',
        sinopse: 'Little Nightmares III é um jogo de aventura imersivo que acompanha a jornada de Low e Alone, dois melhores amigos em busca de uma saída de Lugar Nenhum. Seja 2 jogadores cooperando online ou sozinho com uma I.A., trabalhem juntos para solucionar quebra-cabeças e sobreviver.',
        desenvolvedora: 'Supermassive Games',
        lançamento: '2025',
        valor: 'Não Disponivel',
        link:'https://store.steampowered.com/app/1392860/Little_Nightmares_III/',
        video: 'https://www.youtube.com/embed/XFHOsobwFrA',
        img: 'imagens/little3.jpg',
    },
    {
        id: 9,
        nome: "Marvel's Spider-Man 2",
        sinopse: 'Sejam Melhores. Juntos. O poder incrível do simbionte força Peter Parker e Miles Morales a lutarem desesperadamente para equilibrar suas vidas, amizades e o dever de proteger as pessoas em um capítulo empolgante da aclamada franquia Spider-Man no PC.',
        desenvolvedora: 'Insomniac Games, Nixxes Software',
        lançamento: '30/jan/2025',
        valor: 'Não Disponivel',
        link:'https://store.steampowered.com/app/2651280/Marvels_SpiderMan_2/',
        video: 'https://www.youtube.com/embed/07bcyesxbrg',
        img: 'imagens/spider2.jpg',
    }
]